### ISSUE TITLE
HttpResponce

### ISSUE THREAD

**Issue by SANKETJAIN1111** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#2]
Access to XMLHttpRequest at 'http://localhost:3000/' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by AmitXShukla** [comment]
This error is intentional and is happening because you may not have setup your CORS correctly.

Option 1: Update Server/.env file 
>> I do NOT recommend this approach because it lets anyone localhost access your website., So when you implement this in production, please get rid of localhost entires.
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000,http://localhost:4200

Option 2: Update Server/index.js file 
Un-comment app.use AND Comment other block like

// ****** allow cross-origin requests code START ****** //
>> I do NOT recommend this approach because it lets anyone access your website., So when you implement this in production, please comment this and update your .env CORS with production settings.

app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
// var allowedOrigins = process.env.allowedOrigins.split(',');

// app.use(cors({
//     origin: function (origin, callback) {
        // allow requests with no origin 
        // (like mobile apps or curl requests)
//         if (!origin) return callback(null, true);

//         if (allowedOrigins.indexOf(origin) === -1) {
//             var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
//             return callback(new Error(msg), false);
//         }
//         return callback(null, true);
//     }
// }));

// ****** allow cross-origin requests code END ****** //

**Comment by SANKETJAIN1111** [comment]
Ok , sir i will do this !!

**Comment by nathanchikku** [comment]
I need 6 user login. 2 users to approve leave,employee creation ,attendance etc.
Created by other users.
How to do it.please help me
