### ISSUE TITLE
Http failure response

### ISSUE THREAD

**Issue by smac2k10** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#3]
When I  SignUp-----
Error: Http failure response for http://localhost:3000/alivetracking: 0 Unknown Error
when I login--
Login credentials are not verified. Error: Http failure response for http://localhost:3000/alivetracking: 0 Unknown Error
How can I solve this...

**Comment by AmitXShukla** [comment]
Option 1: Server > index.js 
un-comment line #23 AND comment #25 through #37
Option 2: Server > .env
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com
change this to
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000

**Comment by kittucando** [comment]
> allowedOrigins

NO Such option found in entire code for both options

**Comment by AmitXShukla** [comment]
> > allowedOrigins
> 
> NO Such option found in entire code for both options

This error is intentional and is happening because you may not have setup your CORS correctly.

Option 1: Update Server/.env file

I do NOT recommend this approach because it lets anyone localhost access your website., So when you implement this in production, please get rid of localhost entires.
allowedOrigins=https://elish-erp.firebaseapp.com,https://alivetracking.firebaseapp.com,http://localhost:3000,http://localhost:4200

Option 2: Update Server/index.js file
Un-comment app.use AND Comment other block like

// ****** allow cross-origin requests code START ****** //

I do NOT recommend this approach because it lets anyone access your website., So when you implement this in production, please comment this and update your .env CORS with production settings.

app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
// var allowedOrigins = process.env.allowedOrigins.split(',');

// app.use(cors({
// origin: function (origin, callback) {
// allow requests with no origin
// (like mobile apps or curl requests)
// if (!origin) return callback(null, true);

// if (allowedOrigins.indexOf(origin) === -1) {
// var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
// return callback(new Error(msg), false);
// }
// return callback(null, true);
// }
// }));

// ****** allow cross-origin requests code END ****** //

**Comment by vaidyashubham** [comment]
these solution still not working for me tried this.

**Comment by AmitXShukla** [comment]
Sorry to hear that Vaidya, what part is not working? can you please share error or screen shot where you are stuck at? Angular 8 is out, So I will be updating this repo soon. But please share more details to help me understand what exactly is not working.

**Comment by vaidyashubham** [comment]
when i logged in i got this error "Login credentials are not verified. Error: Http failure response for http://localhost:3000/alivetracking: 0 Unknown Error"
and in console i got this "polyfills.24878f0fc306c9c3ca3c.js:1 OPTIONS http://localhost:3000/alivetracking net::ERR_CONNECTION_REFUSED".
