### ISSUE TITLE
How to convert this to MERN Stack

### ISSUE THREAD

**Issue by dimashiii** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#30]
Great project. If possible can you please help me to build a simple version of this employee attendance and payroll system using MERN stack?

It would be a great help if you could guide me on this

Thank you

**Comment by AmitXShukla** [comment]
Thanks for reaching out.
It’s an old project (still live and working though).

I believe it’s good idea to use React instead of Angular (I assume that what you are referring to by MERN).

Start with building login and next screens/pages in React, 
I'll help you out, and if this works well, I will publish it to my community users.

-Amit
________________________________
From: Dimashi Gunasinghe ***@***.***>
Sent: Tuesday, August 24, 2021 10:52:01 PM
To: AmitXShukla/Employee-Payroll-Salary-App-Angular-11-MEAN-Stack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AmitXShukla/Employee-Payroll-Salary-App-Angular-11-MEAN-Stack] How to convert this to MERN Stack (#30)


Great project. If possible can you please help me to build a simple version of this employee attendance and payroll system using MERN stack?

It would be a great help if you could guide me on this

Thank you
